name: otsukaipoint
description: "おつかいポイント - 親子で楽しむお買い物アプリ"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # JSON Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Backend
  supabase_flutter: ^2.7.0
  flutter_dotenv: ^5.1.0
  
  # UI/UX
  go_router: ^14.6.1
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
  # QR Code
  qr_flutter: ^4.1.0
  # qr_code_scanner: ^1.0.1  # 一時的に無効化
  
  # Utility
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code Generation
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env
    
  # Fonts (一時的にコメントアウト)
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.ttf
  #       - asset: assets/fonts/NotoSansJP-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/NotoSansJP-Light.ttf
  #         weight: 300